name: Auto approve and merge PRs by SlashGordon

on: pull_request_target

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: echo " Issuer ${{ github.event.pull_request.user.login }} -- ${{ github.actor }}"
  dependabot:
    name: Auto Approve and merge PR by SlashGordon
    if: github.event.pull_request.user.login  == 'SlashGordon' || github.actor == 'SlashGordon' 
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.15.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge
          MERGE_RETRIES: "30"
          MERGE_RETRY_SLEEP: "30000"
